# -*- coding: utf-8 -*-
"""visu_de_pontuacao.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U9MKcS7idAhU4lfFR2mIq4Itx3KXhTHW
"""

from matplotlib import pyplot as plt



def P_A():

  vendedores_positivos = []
  vendedores_negativos = []
  p_a_positivo = [] 
  p_a_negativo = []  
  
  quan_vendedor = int(input(f'\nQuantidade de vendedores na loja ?\t'))
  
  for vendedor in range(0, quan_vendedor):
      
      pontuacao = float(input(f'\nQual o P.A do vendedor ?\t'))
      
      if pontuacao >= 2.35:
      
        p_a_positivo.append(pontuacao)
        vendas = input(f'\nQual o nome do vendedor ?\t').upper()
        vendedores_positivos.append(vendas)
      
      else:

        p_a_negativo.append(pontuacao)
        vendas = input(f'\nQual o nome do vendedor ?\t').upper()
        vendedores_negativos.append(vendas)

  media_da_loja = float(f'{sum(p_a_negativo + p_a_positivo)/quan_vendedor:.3f}')
  
  if media_da_loja >= 2.35:
    p_a_positivo.append(media_da_loja)
    vendedores_positivos.append('LOJA')
  
  elif media_da_loja <= 2.35:
    p_a_negativo.append(media_da_loja)
    vendedores_negativos.append('LOJA') 
  
  
  plt.plot(vendedores_negativos, p_a_negativo, color= 'red', marker='o', linestyle='solid')
  plt.plot(vendedores_positivos, p_a_positivo, color= 'blue', marker='o', linestyle='solid')
  plt.title("PA da loja em gráfico de linha")
  plt.ylabel('P.A')
  plt.show()

P_A()