# -*- coding: utf-8 -*-
"""visu_dados_p_a.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U9MKcS7idAhU4lfFR2mIq4Itx3KXhTHW
"""

from matplotlib import pyplot as plt



def P_A():

  vendedores = []
  p_a = []   
  quan_vendedor = int(input(f'\nQuantidade de vendedores na loja com PA vermelho ?\t'))
  
  for vendedor in range(0, quan_vendedor):
      vendas = input(f'\nQual o nome do vendedor ?\t').upper()
      vendedores.append(vendas)
      pontuacao = float(input(f'\nQual o P.A do vendedor ?\t'))
      p_a.append(pontuacao)
  
  media_da_loja = float(f'{sum(p_a)/quan_vendedor:.3f}')
  p_a.append(media_da_loja)
  vendedores.append('LOJA')
  
  plt.plot(vendedores, p_a, color= 'red', marker='o', linestyle='solid')
  plt.title("PA da loja em gráfico")
  plt.ylabel('P.A')
  plt.show()

P_A()